Sprint23
MalinovIgor/sprint8v3 pull request #18
Opened 2024-11-30 14:29 UTC by MalinovIgor

Дорогой ревьюер,
Прошу прокомментировать мои попытки нагнать. 

Ещё пара вопросов, по возможности..
1 есть ли какие-то общепринятые правила, где должен быть биндинг, а где findViewById?
2 как лучше работать с файлами во внутр.хранилище? (во VM или нужно пробрасывать до repository?)

2024-11-30 18:57 UTC, DmitrijEgorow commented
> Дорогой ревьюер, Прошу прокомментировать мои попытки нагнать.
> 
> Ещё пара вопросов, по возможности.. 1 есть ли какие-то общепринятые правила, где должен быть биндинг, а где findViewById? 2 как лучше работать с файлами во внутр.хранилище? (во VM или нужно пробрасывать до repository?)

1) Лучше везде использовать view binding, можно обойтись без findViewById в таком случае
2) Работаем с файлами в репозитории, VM не знает про то, как реализовано сохранение данных

2024-11-30 18:59 UTC, DmitrijEgorow commented
- [ ] Отсутствует нижнеее меню навигации на экране медиатеки
- [ ] Приложение аварийно завершается при возврате назад и последующем клике


https://github.com/user-attachments/assets/9d179f16-f514-480d-a688-91bafb02dffb
```
FATAL EXCEPTION: main  
Process: ru.startandroid.develop.sprint8v3, PID: 8744  
java.lang.IllegalArgumentException: Navigation action/destination ru.startandroid.develop.sprint8v3:id/action_libraryFragment2_to_playlistCreationFragment cannot be found from the current destination Destination(ru.startandroid.develop.sprint8v3:id/playlistCreationFragment) label=PlaylistCreationFragment class=ru.startandroid.develop.sprint8v3.library.ui.fragment.PlaylistCreationFragment  
at androidx.navigation.NavController.navigate(NavController.kt:1540)  
at androidx.navigation.NavController.navigate(NavController.kt:1472)  
at androidx.navigation.NavController.navigate(NavController.kt:1454)  
at ru.startandroid.develop.sprint8v3.library.ui.fragment.PlaylistsFragment.onViewCreated$lambda$1(PlaylistsFragment.kt:56)  
at ru.startandroid.develop.sprint8v3.library.ui.fragment.PlaylistsFragment.[r8](tex://r8)lambda$GQz-yDlYGFGdPUSiK_NYxQThYAM(Unknown Source:0)  
at ru.startandroid.develop.sprint8v3.library.ui.fragment.PlaylistsFragment$$ExternalSyntheticLambda0.onClick(Unknown Source:2)  
at android.view.View.performClick(View.java:7892)  
at android.widget.TextView.performClick(TextView.java:16220)  
at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1218)  
at android.view.View.performClickInternal(View.java:7869)  
at android.view.View.-[$Nest](tex://$Nest)mperformClickInternal(Unknown Source:0)  
at android.view.View$PerformClick.run(View.java:30891)  
at android.os.Handler.handleCallback(Handler.java:942)  
at android.os.Handler.dispatchMessage(Handler.java:99)  
at android.os.Looper.loopOnce(Looper.java:226)
```

2024-11-30 19:00 UTC, DmitrijEgorow commented
- [ ] Не соответствует дизайну
![Screenshot_20241130_213359](https://github.com/user-attachments/assets/6a274011-a480-4fae-8b27-35d44bbf8d70)

- [ ] Фиолетовый цвет не входит в цветовую палитру приложения
![Screenshot_20241130_213508](https://github.com/user-attachments/assets/699b2fdf-8310-4a49-bfdb-e7131286f680)

2024-11-30 19:02 UTC, DmitrijEgorow commented
- [ ] Приложение аварийно завершается
- [ ] Исполнитель может обрезаться, но только если не хватает ширины экрана (за исключением места справа под длительность и точку) – длительность должна быть видна всегда


https://github.com/user-attachments/assets/50eaa47a-ee1d-416c-a4af-1661a428c6a3

2024-11-30 19:03 UTC, DmitrijEgorow commented
- [ ] Нет списка треков в плейлистах
- [ ] 06 минут -> 6 минут
- [ ] Не должно отображаться нижнее меню навигации на экране плейлиста
 

https://github.com/user-attachments/assets/cb3641a7-4dc3-49f2-9427-3111ddef63a3

2024-11-30 19:04 UTC, DmitrijEgorow commented
- [ ] Не должно быть тени у обложек
![Screenshot_20241130_214023](https://github.com/user-attachments/assets/4aa98d04-3e03-4fbb-8ec6-768a24b36b4a)

2024-11-30 19:04 UTC, DmitrijEgorow commented
- [ ] Нет отступа между заголовком плейлиста и его обложкой
![Screenshot_20241130_214205](https://github.com/user-attachments/assets/e8cba8cc-76df-4bfc-ae69-d05d65879055)

2024-11-30 19:05 UTC, DmitrijEgorow commented
- [ ] Устанавливается неправильное изображение плейсхолдера после редактирования

https://github.com/user-attachments/assets/72a68eea-671b-4de9-98ed-1d672bbe64ad

2024-11-30 19:09 UTC, DmitrijEgorow commented on app/src/main/java/ru/startandroid/develop/sprint8v3/library/ui/fragment/PlaylistCreationFragment.kt
> +            binding.btnCreate.text = "Сохранить"
Лучше string-res

2024-11-30 19:09 UTC, DmitrijEgorow commented on app/src/main/java/ru/startandroid/develop/sprint8v3/library/ui/fragment/PlaylistViewFragment.kt
> +            Toast.makeText(requireContext(), "Playlist not found", Toast.LENGTH_SHORT).show()
Лучше string-res
Приложение переведено на англ?

2024-11-30 19:09 UTC, DmitrijEgorow commented on app/src/main/java/ru/startandroid/develop/sprint8v3/search/ui/TrackAdapter.kt
> +    private val tracks: ArrayList<Track> = ArrayList(),
Почему тип не просто List?

2024-11-30 19:09 UTC, DmitrijEgorow commented on app/src/main/res/layout/fragment_playlist_view.xml
> +        android:background="#99000000"
color-res

2024-12-02 22:00 UTC, DmitrijEgorow commented
> * [ ]  Фиолетовый цвет не входит в цветовую палитру приложения
>   ![Screenshot_20241130_213508](https://private-user-images.githubusercontent.com/36837067/391268655-699b2fdf-8310-4a49-bfdb-e7131286f680.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxNzcwOTYsIm5iZiI6MTczMzE3Njc5NiwicGF0aCI6Ii8zNjgzNzA2Ny8zOTEyNjg2NTUtNjk5YjJmZGYtODMxMC00YTQ5LWJmZGItZTcxMzEyODZmNjgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDIxNTk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0ZjUwZGUzYWUyZWNkMzE1ZGRiMjI5MjBhNzg3NDA2NzQzNmFiNWEzNmM4YThmYjA0ZTg0YzQ2YjMyMDFkMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.O1XTgShy6eO6wJ1RRH4GP8IvvmY7J0ni5NyJCbj4f2A)

Актуально

2024-12-02 22:17 UTC, DmitrijEgorow commented
- [ ] Не удается выйти с экрана создания плейлиста
- [ ] Фиолетовый цвет не входит в цветовую палитру приложения

2024-12-02 23:38 UTC, DmitrijEgorow commented
- [ ] Если пользователь находится на экране «Аудиоплеер» и текущий трек добавлен в избранные, то пользователь должен видеть кнопку «Нравится» в выделенном состоянии
- [ ] "6 минут, 1 трек" пишется через точку, а не запятую


https://github.com/user-attachments/assets/2d34343d-4b8f-40d6-a7ea-bbb8f06bf723

2024-12-02 23:40 UTC, DmitrijEgorow commented
- [ ] Приложение аварийно завершается

https://github.com/user-attachments/assets/ce6273b7-da2b-4ff9-9b2d-17a057a4718e

```
FATAL EXCEPTION: main  
Process: ru.startandroid.develop.sprint8v3, PID: 16966  
java.lang.IllegalArgumentException: Navigation action/destination ru.startandroid.develop.sprint8v3:id/action_playlistViewFragment_to_playlistCreationFragment cannot be found from the current destination Destination(ru.startandroid.develop.sprint8v3:id/playlistCreationFragment) label=PlaylistCreationFragment class=ru.startandroid.develop.sprint8v3.library.ui.fragment.PlaylistCreationFragment  
at androidx.navigation.NavController.navigate(NavController.kt:1540)  
at androidx.navigation.NavController.navigate(NavController.kt:1472)  
at androidx.navigation.NavController.navigate(NavController.kt:1454)  
at ru.startandroid.develop.sprint8v3.library.ui.fragment.PlaylistViewFragment.onViewCreated$lambda$10(PlaylistViewFragment.kt:149)  
at ru.startandroid.develop.sprint8v3.library.ui.fragment.PlaylistViewFragment.[r8](tex://r8)lambda$Ujq031x7Hr2Qm66awFqpUQic7GU(Unknown Source:0)  
at ru.startandroid.develop.sprint8v3.library.ui.fragment.PlaylistViewFragment$$ExternalSyntheticLambda3.onClick(Unknown Source:2)  
at android.view.View.performClick(View.java:7892)  
at android.widget.TextView.performClick(TextView.java:16220)  
at android.view.View.performClickInternal(View.java:7869)  
at android.view.View.-[$Nest](tex://$Nest)mperformClickInternal(Unknown Source:0)  
at android.view.View$PerformClick.run(View.java:30891)  
at android.os.Handler.handleCallback(Handler.java:942)  
at android.os.Handler.dispatchMessage(Handler.java:99)  
at android.os.Looper.loopOnce(Looper.java:226)  
at android.os.Looper.loop(Looper.java:313)
```

2024-12-02 23:43 UTC, DmitrijEgorow commented
- [ ] На экране плейлиста не должно быть нижнего меню
- [ ] Если треков нет, то указываем продолжительность плейлиста 0 минут и 0 треков; сейчас под описанием плейлиста такого нет

https://github.com/user-attachments/assets/b520b2b1-f81e-41af-8ae3-5e5ea00bbdf2

2024-12-05 16:43 UTC, MalinovIgor commented
> * [x]  Приложение аварийно завершается
> 
>     * [x]  Исполнитель может обрезаться, но только если не хватает ширины экрана (за исключением места справа под длительность и точку) – длительность должна быть видна всегда
> 
> 
> Screen_recording_20241130_213813.mp4

Вроде везде обрезает
![photo_2024-12-05_19-40-04 (2)](https://github.com/user-attachments/assets/c14068a4-994e-4c38-9935-3b4d5994b022)
![photo_2024-12-05_19-40-04 (3)](https://github.com/user-attachments/assets/282ab720-2443-4037-b984-6f57972f6e5d)
![photo_2024-12-05_19-40-04](https://github.com/user-attachments/assets/89d12261-a70f-45ed-b1c4-eccd9063bf3f)

2024-12-06 13:07 UTC, DmitrijEgorow commented
> * [x]  Не удается выйти с экрана создания плейлиста
> * [x]  Фиолетовый цвет не входит в цветовую палитру приложения
> 
>  IMG_9483.MP4

Про фиолетовый цвет актуально

2024-12-06 13:07 UTC, DmitrijEgorow commented
- [ ] Фиолетовый цвет не входит в цветовую палитру приложения


https://github.com/user-attachments/assets/1c1248c5-c85b-4aff-b5fc-c3df8b8558c0

2024-12-06 13:08 UTC, DmitrijEgorow commented
- [ ] Когда пользователь находится на экране «Плейлист», и в плейлист не был добавлен ни один трек, то пользователь должен видеть сообщением о том, что в этом плейлисте нет треков.

2024-12-06 13:10 UTC, DmitrijEgorow commented
- [ ] Меню должно исчезать и пользователь должен видеть всплывающее сообщение о том, что в данном плейлисте нет списка треков, которым можно поделиться. Сейчас меню не исчезает, только всплывающее сообщение показывается

[Screen_recording_20241206_152846.webm](https://github.com/user-attachments/assets/310d2fdc-dcdb-4d17-bd96-8c184bced5f5)

2024-12-06 13:12 UTC, DmitrijEgorow requested changes

2024-12-06 13:12 UTC, DmitrijEgorow commented on app/src/main/java/ru/startandroid/develop/sprint8v3/library/ui/PlaylistsViewModel.kt
Логику saveImageToPrivateStorage выносим в репозиторий, всю работу с файлами убираем в data слой

2024-12-06 13:23 UTC, DmitrijEgorow commented
- [ ] Исполнитель может обрезаться, но только если не хватает ширины экрана (за исключением места справа под длительность и точку). Исполнитель должен обрезаться не в случайном месте на 2/3 экрана, а только при нехватке ширины экрана
![2024-12-06 16 06 35](https://github.com/user-attachments/assets/dbab5b2c-aaaa-4089-b5ff-e6f5fdb1fdc6)
![2024-12-06 16 06 31](https://github.com/user-attachments/assets/03f6e5b4-e722-43ea-9f1a-b2a655b24614)

2024-12-06 18:01 UTC, MalinovIgor commented
> * [x]  Исполнитель может обрезаться, но только если не хватает ширины экрана (за исключением места справа под длительность и точку). Исполнитель должен обрезаться не в случайном месте на 2/3 экрана, а только при нехватке ширины экрана
>       ![2024-12-06 16 06 35](https://private-user-images.githubusercontent.com/36837067/393262251-dbab5b2c-aaaa-4089-b5ff-e6f5fdb1fdc6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1MDgzNDgsIm5iZiI6MTczMzUwODA0OCwicGF0aCI6Ii8zNjgzNzA2Ny8zOTMyNjIyNTEtZGJhYjViMmMtYWFhYS00MDg5LWI1ZmYtZTZmNWZkYjFmZGM2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDE4MDA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhNTZmMjZhNTJmOGNkODc0MTJhYzg3NGFjZjgzYTUwNTZkZWUxMTY3ZjUwMTZjMjQ5OGQ3N2RmYTNjZTI2NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cE1W2prt209NAjObaRVYqekbxIrVQeSa_MFbwWWCS48)
>       ![2024-12-06 16 06 31](https://private-user-images.githubusercontent.com/36837067/393262274-03f6e5b4-e722-43ea-9f1a-b2a655b24614.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1MDgzNDgsIm5iZiI6MTczMzUwODA0OCwicGF0aCI6Ii8zNjgzNzA2Ny8zOTMyNjIyNzQtMDNmNmU1YjQtZTcyMi00M2VhLTlmMWEtYjJhNjU1YjI0NjE0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDE4MDA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwY2VlZGQwYmQ2NjY4ZWE2NmEwMTA5ZDkwYjAxOWFjZWExYzI3NTQ3MDBiNDgwM2E0OTdlMjM0YWY1YzA5M2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EA4NxAKzpeHiuIXV7oLkQz8Wj9vWMIr_kqKWdTVdank)

прошу прощения, жестко протупил с этим замечанием.

2024-12-07 09:52 UTC, DmitrijEgorow commented on app/src/main/java/ru/startandroid/develop/sprint8v3/library/ui/fragment/PlaylistViewFragment.kt
> +                    sharePlaylist()
И здесь тоже нужно скрывать
```suggestion
                    sharePlaylist()
                    bottomMenuBehavior.state = BottomSheetBehavior.STATE_HIDDEN
```

2024-12-07 09:52 UTC, DmitrijEgorow commented on app/src/main/java/ru/startandroid/develop/sprint8v3/library/ui/PlaylistsViewModel.kt
Здесь saveImageToPrivateStorage не нужен и не используется -> удаляем

2024-12-07 12:56 UTC, MalinovIgor commented on app/src/main/java/ru/startandroid/develop/sprint8v3/library/ui/fragment/PlaylistViewFragment.kt
> +                    sharePlaylist()
Так тут нижнее меню не всплывает?

2024-12-07 20:24 UTC, merged